repos:
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        stages: [commit-msg]
        language: node
        entry: npx --no-install commitlint --edit $1
        additional_dependencies:
          ["@commitlint/cli@15.0.0", "@commitlint/config-conventional@15.0.0"]
      - id: go-fmt
        name: Run go fmt
        entry: go fmt ./...
        language: system
        pass_filenames: false
        stages: [commit]
      - id: go-vet
        name: Run go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        stages: [commit]
      - id: go-test
        name: Run go test
        entry: go test ./...
        language: system
        pass_filenames: false
        stages: [commit]
