repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: Run go fmt
        entry: go fmt ./...
        language: system
        pass_filenames: false
        stages: [commit]
      - id: go-vet
        name: Run go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        stages: [commit]
      - id: go-test
        name: Run go test
        entry: go test ./...
        language: system
        pass_filenames: false
        stages: [commit]
