version: "3.0"
services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tayfur
      - POSTGRES_DB=simple_bank
    # volumes:
    #   - ./.containers/database:/var/lib/postgresql/data
    # ports: 
    #   - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:tayfur@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]